

import { Plan, SkillTreeDef } from './types';

// --- SAFE ALTERNATIVES DATABASE (L4/L5 Friendly) ---
export const SAFE_ALTERNATIVES: Record<string, { name: string; note: string; desc: string }[]> = {
  // Squat Pattern (No spinal load)
  'Box Squats': [
    { name: 'Sit-to-Stands', note: 'Bodyweight only. Back Saver.', desc: 'Sit fully on a bench. Stand up without using hands momentum. Lower slowly.' },
    { name: 'Cable Goblet Squats', note: 'Hold cable at chest. Keep elbows high.', desc: 'Stand facing machine. Hold low pulley handle at chest. Squat down keeping torso upright.' },
    { name: 'Step-Ups', note: 'Unilateral. Easier on back.', desc: 'One foot on bench. Drive through heel. Keep chest tall.' }
  ],
  'Step-Ups': [{ name: 'Box Squats', note: 'Sit fully, then stand.', desc: 'Sit back onto bench/chair. Pause. Drive up.' }],
  
  // Push Pattern
  'Standard Pushups': [
    { name: 'Incline Pushups', note: 'Hands on bench. Back Saver.', desc: 'Easier angle. Keep body in straight plank.' },
    { name: 'Knee Pushups', note: 'Focus on chest contraction.', desc: 'From knees, keep hips down.' },
    { name: 'Scapular Pushups', note: 'Straight arm strength.', desc: 'Plank position. Keep arms straight. Squeeze shoulder blades together, then push them apart.' }
  ],
  
  // Pull Pattern (Progression to Pullup)
  'Gym Monster Lat Pulldown': [
    { name: 'Resistance Band Pulldown', note: 'Lighter load.', desc: 'Kneel. Pull band apart to chest.' },
    { name: 'Inverted Rows', note: 'Set bar waist height.', desc: 'Hang under bar/handles. Keep body straight. Pull chest to bar.' },
    { name: 'Dead Hangs', note: 'Grip strength builder.', desc: 'Just hang from the bar. Keep shoulders active (not by ears).' }
  ],
  'Dead Hangs': [
      { name: 'Active Hangs (Scapular Shrugs)', note: 'Dynamic hanging.', desc: 'Hang from bar. Pull shoulders down away from ears. Relax. Repeat.' }
  ],

  // Core (Anti-Rotation/Flexion - NO Situps for L4/L5)
  'Dead Bugs': [
    { name: 'Dead Bug (Wall Press)', note: 'Max tension.', desc: 'Lie on back, head near wall. Press hands into wall behind you. Perform leg movements. Keeps spine flat.' },
    { name: 'Bird Dogs', note: 'Back Saver Mode.', desc: 'Hands/knees. Reach opposite arm/leg. Neutral spine.' }
  ],
  'Hollow Body Hold': [{ name: 'Dead Bug (Wall Press)', note: 'Safer high-tension core.', desc: 'Lie on back. Press hands into wall. Keep spine glued to floor.' }],
  
  // Flexibility
  'Elephant Walks': [
    { name: 'Seated Hamstring Stretch', note: 'Gentle.', desc: 'Sit on floor. Reach for toes with flat back.' }
  ],
  'Couch Stretch': [
    { name: 'Standing Quad Stretch', note: 'Balance needed.', desc: 'Hold foot behind butt. Squeeze glute.' }
  ],
  'Rower (Intervals)': [
     { name: 'Rower (Steady State)', note: 'Gentle cardio.', desc: 'No sprinting. Just move.' }
  ],
  'Pike Static Hold': [
      { name: 'Downward Dog', note: 'Yoga classic.', desc: 'Hips high. Push floor away.' },
      { name: 'Incline Pike Pushup', note: 'Hands on bench.', desc: 'Easier on shoulders.' }
  ]
};

export const SPEEDIANCE_LIBRARY = [
  "Adductor Bench",
  "Single Leg Extensions",
  "Barbell Front Box Squat",
  "Single Arm Push Press",
  "Seated Alternating Hammer Curl",
  "Seated Dual Handle Hammer Curl",
  "Seated Single Arm Hammer Curl",
  "Standing Alternating Hammer Curl",
  "Standing Dual Handle Hammer Curl",
  "Standing Single Handle Hammer Curl",
  "Barbell Open Knee Hip Thrust",
  "Cable Side Lunge",
  "Seated Dual Handle Low To High Chest Fly",
  "Incline Dual Handle High To Low Chest Press",
  "Standing Single Arm Chest Fly",
  "Kneeling Single Arm High To Low Cross Fly",
  "Standing Dual Handle Reverse Curl",
  "Barbell Narrow Stance Front Squat",
  "Single Arm Deadlift",
  "Single Arm Rack Squat",
  "Dual Handle Narrow Stance Squat",
  "Dual Handle Narrow Stance Front Squat",
  "Single Arm Curtsy Lunge",
  "Seated Single Arm Wrist Curl",
  "Seated Single Arm Wrist Reverse Curl",
  "Seated Dual Handle Wrist Curl",
  "Seated Dual Handle Wrist Reverse Curl",
  "Seated Single Leg Abduction",
  "Standing High Cable Biceps Curl With Rope Attachment",
  "Standing Dual Handle Crossbody Triceps Extension",
  "Standing Single Leg Extension",
  "Standing Single Arm Horizontal Triceps Extension",
  "Half Kneeling Single Arm Preacher Curl",
  "Single Arm Reverse Lunge",
  "Cable Side Step Iso Squat",
  "Standing Dual Handle Marching",
  "Standing Single Arm Marching",
  "Seated Tricep Rope Cross Body Crunch",
  "Standing Tricep Rope Push Twist",
  "Spine Bench Tricep Rope Crunch",
  "Dual Handle Straight Arm Crunch",
  "Straight Arm Barbell Crunch",
  "Kneeling Bench Straight Leg Kickback",
  "Incline Tripod Row",
  "Bent Over Barbell Reverse Grip Straight Arm Pulldown",
  "Incline Dual Handle Straight Arm Pushdown",
  "Seated Barbell Good Morning",
  "Incline Single Arm Chest Press",
  "Single Handle Duck Squat",
  "Seated Barbell Wide Row",
  "Kneeling Dual Handle Low To High Chest Press",
  "Kneeling Dual Handle Low To High Chest Fly",
  "Supine Narrow Grip Dual Handle Chest Press",
  "Standing Single Arm High To Low Chest Press",
  "Kneeling Dual Arm High To Low Chest Press",
  "Kneeling Barbell High To Low Chest Press",
  "Standing Single Arm Shrug",
  "Standing Barbell Chest Press",
  "Standing Barbell Low To High Chest Press",
  "Standing Single Arm Low To High Cross Fly",
  "Seated Single Arm Shoulder Press",
  "Standing Single Arm Crossbody Overhead Triceps Extension",
  "Upper Body Rowing",
  "Lower Body Rowing",
  "Standing Single Arm Bayesian Biceps Curl",
  "Standing Single Arm Pinwheel Curls",
  "Incline Dual Handle Front Raise",
  "Standing Tricep Rope Curl With Wrist Rotation",
  "Kneeling Bent Over Overhead Curl",
  "Standing Single Arm Neutral Grip Front Raise",
  "Standing Single Arm Lateral Raise",
  "Dual Handle Push Press",
  "Single Arm High Pull",
  "Barbell Push Press",
  "Barbell High Pull",
  "Half Kneeling Pallof Press",
  "Dual Handle Dead Bug",
  "Bird Dog Row",
  "Standing Single Leg Pallof Press",
  "Seated Single Arm Side Crunch",
  "Standing Tricep Rope Low To High Woodchops",
  "Standing Tricep Rope High To Low Woodchops",
  "Standing Push Twist",
  "Dual Handle Straight Arm Reverse Crunch",
  "Seated Tricep Rope Crunch",
  "Standing Tricep Rope Shrug",
  "Half Kneeling Single Arm Row",
  "Bent Over Dual Handle Straight Arm Pulldown",
  "Bent Over Single Arm Underhand Row",
  "Bent Over Alternating Row",
  "Bent Over Single Arm Row",
  "Kneeling Alternating Lat Pulldowns",
  "Kneeling Single Arm Lat Pulldown",
  "Kneeling Barbell Reverse Grip Lat Pulldown",
  "Kneeling Barbell Lat Pulldown",
  "Kneeling Dual Handle Lat Pulldown",
  "Seated Barbell Wide Reverse Grip Lat Pulldown",
  "Seated Single Arm Crossbody Row",
  "Seated Single Arm Crossbody Pulldown",
  "Standing Barbell Reverse Grip Row",
  "Standing Barbell Row",
  "Standing Tricep Rope Row",
  "Barbell Reverse Grip Bench Press",
  "Supine Dual Handle Twist Fly",
  "Dual Handle Reverse Grip Bench Press",
  "Dual Handle Triceps Bench Press",
  "Single Arm Bench Press",
  "Kneeling Dual Handle Chest Fly",
  "Standing Alternating Chest Fly",
  "Single Arm Rotator Cuff Internal Rotation",
  "Incline Dual Handle Twist Fly",
  "Incline Barbell Close Grip Chest Press",
  "Seated Dual Handle High To Low Chest Fly",
  "Standing Dual Handle High To Low Chest Press",
  "Standing Dual Handle Toes Out Calf Raises",
  "Standing Dual Handle Toes In Calf Raises",
  "Standing Barbell Toes In Calf Raises",
  "Standing Barbell Calf Raises",
  "Tricep Rope Single Leg Romanian Deadlift",
  "Tricep Rope Staggered Romanian Deadlift",
  "Dual Handle Stiff Leg Deadlift",
  "Barbell Stiff Leg Deadlift",
  "Dual Handle Box Squat",
  "Barbell Box Squat",
  "Dual Handle Front Rack Box Squat",
  "Barbell Front Rack Alternating Reverse Lunges",
  "Barbell Front Rack Split Squat",
  "Single Handle Goblet Alternating Reverse Lunge",
  "Barbell Quarter Squat",
  "Barbell Narrow Stance Squat",
  "Single Arm Overhead Squat",
  "Dual Handle Overhead Squat",
  "Barbell Overhead Squat",
  "Side Plank Hip Abduction",
  "Incline Single Leg Kickback",
  "Dual Handle Straight Arm Glute Bridge",
  "Kneeling Barbell Hip Thrust",
  "Seated Barbell Wrist Curl",
  "Seated Barbell Wrist Reverse Curl",
  "Incline Dual Handle Triceps Push Down",
  "Reverse Narrow Grip Barbell Bench Press",
  "Bent Over Dual Handle Underhand Triceps Kickback",
  "Kneeling Single Arm Underhand Tricep Kickback",
  "Kneeling Single Arm Tricep Kickback",
  "Half Kneeling Single Arm Tricep Kickback",
  "Seated Single Arm Overhead Tricep Extension",
  "Seated Dual Handle Bent Over Kickback",
  "Seated Tricep Rope Overhead Extension",
  "Standing Barbell Reverse Grip Tricep Push Down",
  "Standing Barbell Reverse Grip Tricep Overhead Extension",
  "Standing Single Arm Overhead Tricep Extension",
  "Incline Single Arm Preacher Curl",
  "Incline Barbell High Cable Biceps Curl",
  "Standing High Cable Tricep Rope Curl",
  "Bent Over Reverse Grip Double Handle Row",
  "Incline Alternating Spider Curl",
  "Supine Barbell Overhand Biceps Curl",
  "Supine Barbell High Cable Biceps Curl",
  "Supine Alternating Biceps Curl",
  "Supine Dual Handle Biceps Curl",
  "Supine Barbell Biceps Curl",
  "Tricep Rope Squatting Hammer Curl",
  "Dual Handle Squatting Biceps Curl",
  "Tricep Rope Squatting Bicep Curl",
  "Barbell Squatting Bicep Curl",
  "Seated Dual Handle High Cable Curl",
  "Seated Single Arm Biceps Curl",
  "Seated Alternating Biceps Curl",
  "Standing Barbell Close Grip Biceps Curl",
  "Barbell Drag Curl",
  "Standing Dual Handle Drag Curl",
  "Standing Barbell Wide Grip Biceps Curl",
  "Standing Dual Handle High Cable Curl",
  "Standing Dual Handle Bayesian Biceps Curl",
  "Bent Over Single Arm Wide Row",
  "Seated Elbows Out Barbell Row",
  "Seated Dual Handle Wide Row",
  "Seated Bent Over Single Arm Reverse Fly",
  "Standing Barbell Wide Row",
  "Standing Dual Handle Wide Row",
  "Side Lying Single Arm Lateral Raise",
  "Seated Dual Handle Reverse Grip Lateral Raise",
  "Seated Single Arm Lateral Raise",
  "Seated Single Arm Z Press",
  "Seated Barbell Z Press",
  "Seated Dual Handle Z Press",
  "Seated Bradford Press",
  "Standing Dual Handle Reverse Grip Lateral Raise",
  "Half Kneeling Dual Shoulder Press",
  "Half Kneeling Single Arm Neutral Grip Shoulder Press",
  "Half Kneeling Alternating Neutral Grip Shoulder Press",
  "Incline Supine Dual Handle Neutral Grip Front Raise",
  "Incline Supine Alternating Neutral Grip Front Raise",
  "Incline Supine Single Arm Neutral Grip Front Raise",
  "Seated Dual Handle Neutral Grip Shoulder Press",
  "Seated Barbell Reverse Grip Shoulder Press",
  "Seated Dual Handle Neutral Grip Front Raise",
  "Seated Single Arm Neutral Grip Front Raise",
  "Seated Dual Handle Shoulder Press",
  "Seated Alternating Neutral Grip Front Raise",
  "Standing Barbell Reverse Grip Shoulder Press",
  "Standing Barbell Reverse Grip Front Raise",
  "Standing Alternating Arnold Press",
  "Standing Dual Handle Neutral Grip Front Raise",
  "Supine Barbell Triceps Extension",
  "Standing Cable Hip Abduction",
  "Standing Cable Kickbacks",
  "Kneeling Tricep Rope Pull Through",
  "Seated Double Handle Biceps Curl",
  "Floor Seated Dual Handle Row",
  "Seated Single Arm Row",
  "Barbell Overhead Biceps Curl",
  "Seated Single Arm High Row",
  "Reverse Nordic Curl",
  "Bent Over Dual Handle Triceps Extension",
  "Kneeling Tricep Rope Crunch",
  "Standing Single Arm Overhead Press",
  "Dual Handle Single Leg Romanian Deadlift",
  "Dual Handle Rack Split Squat",
  "Standing Single Arm Biceps Curls",
  "Bent Over Tricep Rope Overhead Triceps Extension",
  "Standing Single Arm Low To High Chest Press",
  "Single Arm Rack Split Squat",
  "Standing Single Arm Row",
  "Single Arm Split Squat",
  "Barbell Staggered Romanian Deadlift",
  "Barbell Single Leg Romanian Deadlift",
  "Kneeling Cable Kickback",
  "Single Arm Single Leg Romanian Deadlift",
  "Single Arm Staggered Romanian Deadlift",
  "Barbell Zercher Split Squat",
  "Kneeling Tricep Rope Hammer Curl",
  "Dual Handle Staggered Deadlift",
  "Half Kneeling Low To High Woodchops",
  "Belt Lateral Split Squat",
  "Belt Reverse Lunges",
  "Barbell Reverse Lunge",
  "Dragon Bench",
  "Seated Leg Curl",
  "Adductor Floor Upper",
  "Lunge Horizontal Press",
  "Adductor Floor Low",
  "Unilateral Aerobic Skiing",
  "HandsWU-8",
  "Pallof Press",
  "Standing Tricep Rope Upright Row",
  "Standing Leg Curl",
  "Abductor Floor",
  "Standing Cable External Rotation",
  "Prone Incline Dual Handle Straight Arm Push Down",
  "Standing Horizontal Woodchops",
  "Bent Over Tricep Rope Straight Arm Pulldown",
  "Dual Handle Bulgarian Split Squat",
  "Single Arm Single Leg Romanian Deadlift (L9)",
  "Lateral Lunge Rear Fly",
  "Prone Single Leg Curl",
  "Dual Handle Split Squat",
  "Hip Torsion",
  "Barbell Single Leg Hip Thrust",
  "Adductor Lying",
  "Lateral Lunge With Pallof Press",
  "Lunge With Horiz Pull And Overhead Press",
  "Side Leg Pull",
  "Bench Kickback",
  "Incline Bench Single Leg Curl",
  "Standing Single Leg Calf Raise",
  "Lateral Lunge Pallof Press With Rotation",
  "Weighted Tiger Combination Stretch",
  "Weighted Tiger Pose",
  "Pes Pull",
  "Single Handle Low To High Woodchops",
  "Side Lying Knee Flexion With Adduction",
  "Kneeling Shoulder Internal Rotation",
  "Seated Single Arm Concentration Curl",
  "Forearm Plank Cable Pull",
  "Quadriceps Flatbench",
  "Handle Lateral Split Squat",
  "Single Leg Ground Press High Position",
  "Single Leg Pulldown Low Position",
  "Frog Leg",
  "Squat Position + Alternating Reverse Lunges",
  "Seated Single Arm Lat Pulldown",
  "Side Lying Hip Abduction",
  "Half Kneeling Tricep Rope Low To High Cable Pull",
  "Dual Handle Reverse Lunge",
  "Bent Over Single Arm Reverse Fly",
  "Half Kneeling Tricep Rope High To Low Cable Pull",
  "Leaning Single Arm Lateral Raise",
  "Standing Single Arm Neutral Grip Front Raise",
  "Standing Single Leg Hip Flexion",
  "Standing High To Low Woodchops",
  "Dual Handle Staggered Romanian Deadlift",
  "Single Arm Bulgarian Split Squat",
  "Half Kneeling Single Arm Underhand Lat Pulldown",
  "Standing Single Leg Hip Extension",
  "Standing Single Arm Underhand Triceps Push Down",
  "Standing Single Arm Triceps Push Down",
  "Standing Cable Hip Abduction Floor",
  "Belt Bulgarian Split Squat",
  "Belt Split Squat",
  "Single Arm Cross Body Triceps Push Down",
  "Incline Bench Single Leg Reverse Crunch",
  "Standing Single Arm Biceps Curl",
  "Standing Single Arm Chest Press",
  "Half Kneeling Horizontal Woodchops",
  "Single Handle High Pull 45 Degrees",
  "Single Handle High Pull 60 Degrees",
  "Single Arm Romanian Deadlift",
  "Single Handle Low Pull 60 Degrees",
  "Iso Squat Cable Side Step",
  "Quadriceps Cross Flatbench",
  "Squat With Single Arm Chest Press",
  "Bench Kneeling Bent Over Row",
  "Side Plank Cable Press",
  "Incline Straight Leg Kickback",
  "Standing Shoulder Internal Rotation",
  "Adductor Bench Upper",
  "Forearm Reverse Curl",
  "Standing Cable Hip Abduction",
  "Leg Curl Floor",
  "Seated Single Handle Low Pull",
  "Adductor Lying Top",
  "Single Arm Staggered Deadlift",
  "Leg Curl Cross Flatbench",
  "Seated Single Handle High Pull",
  "Handle Side Bend",
  "Kneeling Bench Bent Leg Kickback",
  "Barbell Bulgarian Split Squat",
  "Pallof Press To Woodchops",
  "Standing Cable Kickback Floor",
  "Side Plank Row",
  "Kneeling Incline Single Arm Lateral Raise",
  "Forearm Rotation",
  "Kneeling Contralateral Resistance Swim",
  "Incline Single Arm 45 Degrees Row",
  "Pes Push",
  "Belt Alternating Reverse Lunge",
  "Barbell Alternating Reverse Lunge",
  "Dual Handle Alternating Reverse Lunge",
  "Barbell Good Morning",
  "Supine Dual Handle Triceps Extension",
  "Barbell Thruster",
  "Straight Arm Barbell Crunch Floor",
  "Tricep Rope Romanian Deadlift",
  "Tricep Rope Bent Over Row",
  "Standing Dual Handle Triceps Push Down",
  "Seated Dual Handle Underhand Row",
  "Seated Barbell Reverse Grip Row",
  "Supine Dual Handle Reverse Fly",
  "Incline Tricep Rope Straight Arm Pushdown",
  "Incline Supine Barbell Overhead Triceps Extension",
  "Incline Prone Dual Handle Wide Row",
  "Incline Bench Spider Curl",
  "Incline Tricep Rope Triceps Push Down",
  "Seated Barbell Row",
  "Incline Prone Dual Handle Row",
  "Kneeling Dual Handle Triceps Dips",
  "Prone Incline Dual Handle Lateral Raise",
  "Incline Dual Handle Front Raise",
  "Kneeling Tricep Rope Overhead Triceps Extension",
  "Seated Barbell Reverse Grip Lat Pulldown",
  "Kneeling Tricep Rope Lat Pulldown",
  "Kneeling Dual Handle High To Low Chest Fly",
  "Tricep Rope Goblet Squat",
  "Standing Tricep Rope Overhead Triceps Extension",
  "Seated Barbell Calf Raise",
  "Dual Handle Zottman Curl",
  "Standing Tricep Rope Face Pull Middle Delts",
  "Standing Tricep Rope Face Pull Rear Delts",
  "Incline Supine Barbell Biceps Curl",
  "Incline Dual Handle Chest Fly",
  "Bent Over Dual Handle Wide Row",
  "Incline Dual Handle Chest Fly Floor",
  "Belt Squat",
  "Handle Goblet Squat",
  "Belt Hip Thrust",
  "Incline Dual Handle Chest Press",
  "Incline Dual Handle High To Low Chest Fly",
  "Standing Dual Handle Arnold Press",
  "Standing Barbell Overhead Biceps Curl",
  "Bent Over Barbell Straight Arm Pulldown",
  "Bent Over Dual Handle Reverse Fly",
  "Standing Dual Handle Front Raise",
  "Standing Dual Handle Shoulder Press",
  "Bent Over Reverse Grip Barbell Row",
  "Dual Handle Alternating Biceps Curl",
  "Crunch From Top",
  "Standing Tricep Rope Pull Through",
  "Supine Leg Press",
  "Dual Handle Standing Lower Cross Pull",
  "Seated Incline Dual Handle Biceps Curl",
  "Lying Alternating Glute Bridges",
  "Seated Barbell Shoulder Press",
  "Standing Alternating Chest Press",
  "Bent Over Dual Handle Triceps Extension Floor",
  "Incline Dual Handle Underhand Row",
  "Alternating Straight Leg Press Down",
  "Seated Alternating Shoulder Press",
  "Aerobic Skiing Alternate Arm Pulls",
  "Dual Handle Rhomboids Butterfly",
  "Standing Dual Handle Chest Fly",
  "Standing Barbell Upright Row",
  "Dual Handle Calf Raises",
  "Incline Dual Handle Cross Chest Fly",
  "LegsWU-8",
  "Bench Supine Cable Scissor Kick",
  "Seated Bent Over Dual Handle Reverse Fly",
  "Standing Dual Handle Lateral Raise",
  "Standing Dual Handle High To Low Chest Fly",
  "Barbell Deadlift",
  "Dual Handle Romanian Deadlift",
  "Seated Dual Handle Pulldown",
  "Seated Dual Handle Push Down",
  "Squat Position Alternating Reverse Lunges",
  "Standing Dual Handle Row",
  "Seated Barbell Lat Pulldown",
  "Dual Handle Bent Over Row",
  "LegsWU-5",
  "Aerobic Skiing Straight Arms",
  "LegsWU-2",
  "Seated Incline Cable Reverse Crunch",
  "LegsWU-4",
  "Alternating Arm Circles On A Incline Bench",
  "Hands Rotation In",
  "Barbell Romanian Deadlift",
  "HandsWU-6",
  "Barbell Hip Thrust",
  "LegsWU-1",
  "LegsWU-3",
  "Incline Barbell Front Raise",
  "Standing Barbell Triceps Push Down",
  "Standing Tricep Rope Hammer Curl",
  "Hands Rotation Out",
  "Seated Incline Barbell Crunch",
  "Barbell Bent Over Row",
  "Standing Tricep Rope Triceps Pushdown",
  "Standing Barbell Shoulder Press",
  "Seated Incline Alternating Biceps Curl",
  "Standing Dual Handle Chest Press",
  "Seated Alternating Row",
  "Standing Dual Handle Low To High Chest Fly",
  "Standing Barbell Biceps Curl",
  "Incline Dual Handle Shrug",
  "Barbell Pull Over Fitball",
  "Y Front Raise",
  "Crunch Lying From Bottom",
  "Single Handle Low Pull 45 Degrees Left",
  "Supine Incline Dual Handle Lateral Raise",
  "Barbell Front Squat",
  "HandsWU-4",
  "Dual Handle Thruster",
  "Supine Incline Barbell Upright Row",
  "Barbell Zercher Squat",
  "Incline Dual Handle Low To High Chest Fly",
  "Seated Alternating Lat Pulldown",
  "Barbell Narrow Grip Bench Press",
  "DYAD",
  "Dual Handle Front Squat",
  "Barbell Roman Chair Pull",
  "Dual Handle Deadlift",
  "Dual Handle Bench Press",
  "Dual Handle Rhomboids Butterfly Lower",
  "Incline Barbell Bench Press",
  "Barbell Pull Over Cross Bench",
  "Barbell Upper Pull",
  "Standing Barbell Shrugs",
  "HandsWU-2",
  "HandsWU-5",
  "Standing Alternating Row",
  "Leg Rotation In",
  "Incline Dual Handle Cross Reverse Fly",
  "Standing Dual Handle Biceps Curl",
  "Dual Handle Alternating Bench Press",
  "Aerobic Rowing",
  "Kneeling Dual Handle Underhand Lat Pulldown",
  "Breaststroke",
  "Seated Dual Handle Arnold Press",
  "Standing Dual Handle Low To High Chest Press",
  "HandsWU-3",
  "Single Handle Low Pull 45 Degrees Right",
  "Barbell Supine Straight Arm Pullover",
  "Standing Barbell Front Raise",
  "Standing Alternating Shoulder Press",
  "Barbell Pull Over Slant Bench",
  "HandsWU-1",
  "HandsWU-7",
  "Wide Grip Barbell Row",
  "Barbell Bench Press",
  "Narrow Grip Barbell Pull",
  "Bent Over Barbell Wide Row",
  "Seated Dual Handle Lateral Raise",
  "Standing Barbell Overhead Triceps Extension",
  "Barbell Pull Over Floor",
  "Dual Handle Slant Bench Press Lower",
  "Aerobic Skiing Bent Arms",
  "Standing Dual Handle Shrug",
  "Barbell Squat",
  "Seated Dual Handle Neutral Grip Row",
  "Leg Rotation Out",
  "Incline Barbell Straight Arm Pushdown",
  "Barbell Pull Over Behind The Neck",
  "Seated Dual Handle Front Raise",
  "Supine Dual Handle Chest Fly",
  "Aerobic Skiing (Seated Position)"
];

export const SKILL_TREES: SkillTreeDef[] = [
  {
    id: 'pull_mastery',
    title: 'Pull Strength: To The Muscle Up',
    description: 'Road to the ultimate calisthenics flex.',
    nodes: [
      { level: 1, title: 'Dead Hang', criteria: 'Hold for 30s' },
      { level: 2, title: 'Active Hang', criteria: '3x10 Scapular Pulls' },
      { level: 3, title: 'Inverted Rows', criteria: '3x8 (Body Horizontal)' },
      { level: 4, title: 'Negative Pull-ups', criteria: '3x5 (5s descent)' },
      { level: 5, title: 'Assisted Pull-up', criteria: 'Band/Machine (Full ROM)' },
      { level: 6, title: 'Chin-Up', criteria: '1 Strict Rep (Underhand)' },
      { level: 7, title: 'THE PULL-UP', criteria: '1 Strict Rep (Overhand)' },
      { level: 8, title: 'High Pull-Up', criteria: 'Chest to Bar' },
      { level: 9, title: 'Explosive Pull-Up', criteria: 'Waist to Bar' },
      { level: 10, title: 'THE MUSCLE UP', criteria: '1 Rep (Over the bar)' }
    ]
  },
  {
    id: 'flexibility_mastery',
    title: 'Mobility: The Front Split',
    description: 'Unlocking hips and hamstrings.',
    nodes: [
      { level: 1, title: 'Touch Knees', criteria: 'Standing, Straight legs' },
      { level: 2, title: 'Elephant Walks', criteria: '30 reps (Palms on block)' },
      { level: 3, title: 'Touch Toes', criteria: 'Fingertips to floor' },
      { level: 4, title: 'Palms to Floor', criteria: 'Full palm contact' },
      { level: 5, title: 'Couch Stretch', criteria: '60s hold/side' },
      { level: 6, title: 'Deep Lunge', criteria: 'Hips below knee level' },
      { level: 7, title: 'Pigeon Pose', criteria: 'Shin parallel to front' },
      { level: 8, title: 'Frog Stretch', criteria: 'Inner thighs flat' },
      { level: 9, title: 'Supported Split', criteria: 'Using blocks/hands' },
      { level: 10, title: 'FULL SPLITS', criteria: 'Hips on floor' }
    ]
  },
  {
    id: 'core_mastery',
    title: 'Core: The L-Sit',
    description: 'Iron abs protected spine.',
    nodes: [
      { level: 1, title: 'Bird Dogs', criteria: 'Perfect stability (No wobble)' },
      { level: 2, title: 'Dead Bugs', criteria: '3x10 Slow & Controlled' },
      { level: 3, title: 'Plank', criteria: '60s Hold (Good form)' },
      { level: 4, title: 'Hollow Hold', criteria: '30s Hold (Low back glued)' },
      { level: 5, title: 'Hanging Knee Raise', criteria: '3x10 (No swinging)' },
      { level: 6, title: 'L-Sit Tuck', criteria: '10s Hold (Floor/Parallettes)' },
      { level: 7, title: 'L-Sit One Leg', criteria: '5s Hold/side' },
      { level: 8, title: 'Toes to Bar', criteria: '3 Strict Reps' },
      { level: 9, title: 'L-Sit (Bent Knees)', criteria: '15s Hold' },
      { level: 10, title: 'FULL L-SIT', criteria: '10s Hold (Legs Straight)' }
    ]
  },
  {
    id: 'handstand_mastery',
    title: 'Skill: The Handstand',
    description: 'Inversion and balance.',
    nodes: [
      { level: 1, title: 'Pike Pushup Hold', criteria: '30s Hold' },
      { level: 2, title: 'Elevated Pike', criteria: 'Feet on box/chair 30s' },
      { level: 3, title: 'Wall Walk', criteria: 'Walk feet up wall' },
      { level: 4, title: 'Chest-to-Wall', criteria: '30s Hold (Nose to wall)' },
      { level: 5, title: 'Back-to-Wall', criteria: 'Balance drills' },
      { level: 6, title: 'Crow Pose', criteria: '10s Balance' },
      { level: 7, title: 'Wall Kick-Ups', criteria: 'Consistent entry' },
      { level: 8, title: 'Freestanding Kick-up', criteria: 'Find balance point' },
      { level: 9, title: 'Handstand', criteria: '5s Freestanding Hold' },
      { level: 10, title: 'Handstand Pushup', criteria: '1 Rep (Wall Assisted)' }
    ]
  }
];

export const INITIAL_PLAN: Plan = {
  monday: {
    id: 'monday',
    title: "Monday: Full Body & Core Foundation",
    subtitle: "Focus: Controlled movements, protecting back.",
    sections: [
      {
        title: "Warmup",
        items: [
           { id: 'w1', name: "Rower or Elliptical", sets: "1", reps: "5 min", type: 'cardio', val: 5, unit: 'min', note: "Low intensity.", desc: "Get blood flowing." },
           { id: 'w2', name: "Cat-Cow Stretch", sets: "1", reps: "10 reps", type: 'mobility', val: 0, unit: '', note: "Gentle spinal movement.", desc: "Arch spine then round spine." },
           { id: 'w3', name: "Arm Circles", sets: "1", reps: "10 reps", type: 'mobility', val: 0, unit: '', note: "Forward & Backward.", desc: "Mobilize shoulders." },
           { id: 'w4', name: "Leg Swings", sets: "1", reps: "10 reps", type: 'mobility', val: 0, unit: '', note: "Front/Back & Side/Side.", desc: "Mobilize hips." }
        ]
      },
      {
        title: "Main Workout",
        items: [
          { id: 'm1', name: "Incline Push-ups", sets: "3", reps: "10-15 reps", type: 'strength', val: 0, unit: '', note: "Hands on bench.", desc: "Focus on chest reaching surface, full control." },
          { id: 'm2', name: "Assisted Rows (Gym Monster)", sets: "3", reps: "10-15 reps", type: 'strength', val: 0, unit: 'lbs', note: "Set cable low.", desc: "Grab handles, lean back slightly, pull to lower chest, squeeze shoulder blades." },
          { id: 'm3', name: "Dead Bugs", sets: "3", reps: "8-12/side", type: 'core', val: 0, unit: '', note: "Lower back pressed to floor.", desc: "Slowly extend opposite arm/leg without arching back." },
          { id: 'm4', name: "Glute Bridges", sets: "3", reps: "12-15 reps", type: 'strength', val: 0, unit: '', note: "Squeeze glutes.", desc: "Lift hips, form straight line shoulders to knees." },
          { id: 'm5', name: "Bodyweight Squats", sets: "3", reps: "10-15 reps", type: 'strength', val: 0, unit: '', note: "Chest up.", desc: "Controlled movement, only go as deep as comfortable with no back strain." }
        ]
      },
      {
        title: "Cool-down",
        items: [
            { id: 'cd1', name: "Child's Pose", sets: "1", reps: "60 sec", type: 'mobility', val: 60, unit: 'sec', note: "Rest for back.", desc: "Hips to heels." },
            { id: 'cd2', name: "Kneeling Hip Flexor Stretch", sets: "1", reps: "60 sec/side", type: 'mobility', val: 60, unit: 'sec', note: "One knee down.", desc: "Push hips forward gently." },
            { id: 'cd3', name: "Lying Hamstring Stretch", sets: "1", reps: "60 sec/side", type: 'mobility', val: 60, unit: 'sec', note: "Lie on back.", desc: "Lift leg straight up, pull gently." },
            { id: 'cd4', name: "Chest Stretch", sets: "1", reps: "60 sec/side", type: 'mobility', val: 60, unit: 'sec', note: "Hand against wall.", desc: "Gently rotate away." }
        ]
      }
    ]
  },
  tuesday: {
    id: 'tuesday',
    title: "Tuesday: Active Recovery & Flexibility",
    subtitle: "Steady cardio and deep stretching.",
    sections: [
        {
            title: "Cardio",
            items: [
                { id: 't1', name: "Elliptical or Rower", sets: "1", reps: "30-45 min", type: 'cardio', val: 45, unit: 'min', note: "Steady, moderate pace.", desc: "Zone 2 cardio." }
            ]
        },
        {
            title: "Flexibility Session",
            items: [
                { id: 't2', name: "Cat-Cow Stretch", sets: "1", reps: "10 reps", type: 'mobility', val: 0, unit: '', note: "Gentle spinal mobility.", desc: "" },
                { id: 't3', name: "Kneeling Hip Flexor Stretch", sets: "2", reps: "45-60 sec/side", type: 'mobility', val: 60, unit: 'sec', note: "Open hips.", desc: "" },
                { id: 't4', name: "Lying Hamstring Stretch", sets: "2", reps: "45-60 sec/side", type: 'mobility', val: 60, unit: 'sec', note: "Target hamstrings.", desc: "" },
                { id: 't5', name: "Pigeon Pose", sets: "2", reps: "45-60 sec/side", type: 'mobility', val: 60, unit: 'sec', note: "Go easy.", desc: "Modified if needed." },
                { id: 't6', name: "Child's Pose", sets: "1", reps: "2 min", type: 'mobility', val: 2, unit: 'min', note: "Relax.", desc: "" }
            ]
        }
    ]
  },
  wednesday: {
    id: 'wednesday',
    title: "Wednesday: Upper Body & Core Strength",
    subtitle: "Push/Pull balance.",
    sections: [
        {
            title: "Warmup",
            items: [
                { id: 'w_wed', name: "Rower (Warmup)", sets: "1", reps: "5 min", type: 'cardio', val: 5, unit: 'min', note: "Light pace.", desc: "" },
                { id: 'w_dyn', name: "Dynamic Stretches", sets: "1", reps: "Complete routine", type: 'mobility', val: 0, unit: '', note: "Cat-Cow, Arm Circles.", desc: "" }
            ]
        },
        {
            title: "Strength",
            items: [
                { id: 'w1', name: "Knee Push-ups", sets: "3", reps: "10-15 reps", type: 'strength', val: 0, unit: '', note: "Or Wall Push-ups.", desc: "Focus on slow, controlled descent – 2 seconds down." },
                { id: 'w2', name: "Gym Monster Lat Pulldown", sets: "3", reps: "10-15 reps", type: 'strength', val: 0, unit: 'lbs', note: "Feel the lats.", desc: "Pull to upper chest, control the release." },
                { id: 'w3', name: "Plank", sets: "3", reps: "30-60 sec", type: 'core', val: 60, unit: 'sec', note: "Knees or Full.", desc: "Straight line, brace core, no hip sagging." },
                { id: 'w4', name: "Side Plank", sets: "3", reps: "20-40 sec/side", type: 'core', val: 40, unit: 'sec', note: "Obliques.", desc: "Knees or Full." },
                { id: 'w5', name: "Bicep Curls (Gym Monster)", sets: "3", reps: "12-15 reps", type: 'strength', val: 0, unit: 'lbs', note: "Light weight.", desc: "Focus on slow, controlled movement." }
            ]
        },
        {
            title: "Cool-down",
            items: [
                { id: 'cd_wed', name: "Static Stretches", sets: "1", reps: "Routine", type: 'mobility', val: 0, unit: '', note: "See Monday cool-down.", desc: "" }
            ]
        }
    ]
  },
  thursday: {
    id: 'thursday',
    title: "Thursday: Lower Body & Core Stability",
    subtitle: "Leg endurance and stability.",
    sections: [
        {
            title: "Warmup",
            items: [
                { id: 'w_thu', name: "Elliptical (Warmup)", sets: "1", reps: "5 min", type: 'cardio', val: 5, unit: 'min', note: "", desc: "" },
                { id: 'w_dyn2', name: "Dynamic Stretches", sets: "1", reps: "Routine", type: 'mobility', val: 0, unit: '', note: "Leg swings focus.", desc: "" }
            ]
        },
        {
            title: "Strength",
            items: [
                { id: 'th1', name: "Goblet Squat", sets: "3", reps: "10-15 reps", type: 'strength', val: 0, unit: 'lbs', note: "Bodyweight or very light.", desc: "Perfect form, chest up, control movement." },
                { id: 'th2', name: "Wall Sit", sets: "3", reps: "30-60 sec", type: 'strength', val: 60, unit: 'sec', note: "Quad endurance.", desc: "No spinal load." },
                { id: 'th3', name: "Calf Raises", sets: "3", reps: "15-20 reps", type: 'strength', val: 0, unit: '', note: "Squeeze top.", desc: "Raise up onto balls of feet." },
                { id: 'th4', name: "Hollow Body Hold (Modified)", sets: "3", reps: "20-40 sec", type: 'core', val: 40, unit: 'sec', note: "Low back on floor.", desc: "Arms overhead, legs extended. Bend knees if needed." },
                { id: 'th5', name: "Bird Dog", sets: "3", reps: "8-12/side", type: 'core', val: 0, unit: '', note: "Neutral spine.", desc: "Extend opposite arm and leg, keep hips level." }
            ]
        },
        {
             title: "Cool-down",
             items: [
                 { id: 'cd_thu', name: "Static Stretches", sets: "1", reps: "Routine", type: 'mobility', val: 0, unit: '', note: "", desc: "" }
             ]
        }
    ]
  },
  friday: {
    id: 'friday',
    title: "Friday: Full Body & Calisthenics",
    subtitle: "Foundation for advanced moves.",
    sections: [
        {
            title: "Warmup",
            items: [
                { id: 'w_fri', name: "Rower/Elliptical", sets: "1", reps: "5 min", type: 'cardio', val: 5, unit: 'min', note: "", desc: "" },
                { id: 'w_dyn3', name: "Dynamic Stretches", sets: "1", reps: "Routine", type: 'mobility', val: 0, unit: '', note: "", desc: "" }
            ]
        },
        {
            title: "Strength",
            items: [
                { id: 'f1', name: "Incline Push-ups", sets: "3", reps: "8-12 reps", type: 'strength', val: 0, unit: '', note: "Lower incline if possible.", desc: "Perfect form." },
                { id: 'f2', name: "Assisted Pull-ups (Gym Monster)", sets: "3", reps: "5-8 reps", type: 'strength', val: 0, unit: 'lbs', note: "Controlled pull.", desc: "Slow eccentric phase. Squeeze back." },
                { id: 'f3', name: "Australian Rows (Gym Monster)", sets: "3", reps: "10-15 reps", type: 'strength', val: 0, unit: '', note: "Set cable high.", desc: "Lie back, pull chest to bar/handles." },
                { id: 'f4', name: "Bodyweight Lunges", sets: "3", reps: "8-10/leg", type: 'strength', val: 0, unit: '', note: "Controlled steps.", desc: "Keep torso upright." },
                { id: 'f5', name: "Reverse Crunches", sets: "3", reps: "10-15 reps", type: 'core', val: 0, unit: '', note: "Gentle.", desc: "Lift hips off floor, knees to chest. No momentum." }
            ]
        },
        {
             title: "Cool-down",
             items: [
                 { id: 'cd_fri', name: "Static Stretches", sets: "1", reps: "Routine", type: 'mobility', val: 0, unit: '', note: "", desc: "" }
             ]
        }
    ]
  },
  saturday: {
    id: 'saturday',
    title: "Saturday: Active Recovery & Deep Stretch",
    subtitle: "Targeting splits goals.",
    sections: [
        {
            title: "Cardio",
            items: [
                { id: 's1', name: "Elliptical or Rower", sets: "1", reps: "30-45 min", type: 'cardio', val: 45, unit: 'min', note: "Moderate pace.", desc: "" }
            ]
        },
        {
            title: "Deep Flexibility",
            items: [
                { id: 's2', name: "Cat-Cow Stretch", sets: "1", reps: "10 reps", type: 'mobility', val: 0, unit: '', note: "Warmup spine.", desc: "" },
                { id: 's3', name: "Kneeling Hip Flexor Stretch", sets: "2", reps: "45-90 sec/side", type: 'mobility', val: 90, unit: 'sec', note: "Deep hold.", desc: "" },
                { id: 's4', name: "Lying Hamstring Stretch", sets: "2", reps: "45-90 sec/side", type: 'mobility', val: 90, unit: 'sec', note: "Deep hold.", desc: "" },
                { id: 's5', name: "Pigeon Pose", sets: "2", reps: "45-90 sec/side", type: 'mobility', val: 90, unit: 'sec', note: "Deep hold.", desc: "" },
                { id: 's6', name: "Frog Pose", sets: "2", reps: "45-90 sec", type: 'mobility', val: 90, unit: 'sec', note: "Inner thighs.", desc: "Go gently." },
                { id: 's7', name: "Butterfly Stretch", sets: "2", reps: "45-90 sec", type: 'mobility', val: 90, unit: 'sec', note: "Push knees to floor.", desc: "" },
                { id: 's8', name: "Child's Pose", sets: "1", reps: "2 min", type: 'mobility', val: 2, unit: 'min', note: "Recover.", desc: "" }
            ]
        }
    ]
  },
  sunday: {
    id: 'sunday',
    title: "Sunday: Rest",
    subtitle: "Complete rest or light walk.",
    sections: []
  }
};
